import {z} from "zod";
import type {Tool, ToolContext} from "../types.js";
import {displayToolPath, resolveToolPath} from "../shared/paths.js";
import {findMatches, type MatchSpan} from "./strMatch.js";
import {normalizeFileText} from "../shared/fileState.js";
import {createFileChange} from "../../fileChanges/index.js";
import {commitFileWrite} from "../shared/fileWrite.js";
import {readFileSnapshot} from "../shared/fileSnapshot.js";

const editSchema = z.object({
    old_string: z.string().min(1).describe("Exact text to replace in the current file. Include enough context to identify one location."),
    new_string: z.string().describe("Replacement text."),
    replace_all: z.boolean().default(false).describe("Replace every match; requires a full file read."),
}).strict();

const inputSchema = z.object({
    path: z.string().describe("Path of the file to edit."),
    edits: z.array(editSchema).min(1).max(100).describe("Non-overlapping replacements against the same current file version. Use one item for a single replacement."),
}).strict();

type Edit = z.infer<typeof editSchema>;
interface Replacement extends MatchSpan {
    newString: string;
    editIndex: number;
}
interface EditValidation {
    originalContent: string;
    normalizedContent: string;
    changedSinceRead: boolean;
    replacements: Replacement[];
}

/** Match normalized lines, but change only the selected bytes in the original file. */
function applyReplacements(original: string, replacements: readonly Replacement[]): string {
    let raw = 0, normalized = 0, previousEnd = 0;
    const parts: string[] = [];
    const offset = (target: number): number => {
        while (normalized < target) {
            raw += original[raw] === "\r" && original[raw + 1] === "\n" ? 2 : 1;
            normalized++;
        }
        return raw;
    };
    for (const span of replacements) {
        const start = offset(span.start), end = offset(span.end);
        const newline = /\r\n|\r|\n/g;
        newline.lastIndex = start;
        const following = newline.exec(original);
        const previous = Math.max(original.lastIndexOf("\n", start - 1), original.lastIndexOf("\r", start - 1));
        const ending = following?.[0] ?? (previous < 0 ? "\n" : original[previous] === "\r"
            ? "\r" : original[previous - 1] === "\r" ? "\r\n" : "\n");
        const replacement = normalizeFileText(original.slice(start, end)) === span.newString
            ? original.slice(start, end) : span.newString.replace(/\n/g, ending);
        parts.push(original.slice(previousEnd, start), replacement);
        previousEnd = end;
    }
    parts.push(original.slice(previousEnd));
    return parts.join("");
}

function lineRange(content: string, span: MatchSpan): string {
    const start = content.slice(0, span.start).split("\n").length;
    const end = content.slice(0, Math.max(span.start, span.end - 1)).split("\n").length;
    return start === end ? String(start) : `${start}-${end}`;
}

async function validateEdits(
    path: string,
    edits: readonly Edit[],
    ctx: ToolContext
): Promise<{ ok: true; value: EditValidation } | { ok: false; message: string }> {
    let originalContent: string;
    try {
        const snapshot = await readFileSnapshot(path);
        originalContent = snapshot.content.toString("utf8");
        if (snapshot.content.includes(0) || !Buffer.from(originalContent).equals(snapshot.content)) {
            throw new Error("edit_file requires valid UTF-8 text without NUL bytes");
        }
    } catch (err) {
        return {
            ok: false,
            message: `Failed to read file: ${err instanceof Error ? err.message : String(err)}`,
        };
    }

    const state = ctx.fileState.check(path, originalContent);


    const normalizedContent = normalizeFileText(originalContent);
    const replacements: Replacement[] = [];
    for (const [editIndex, edit] of edits.entries()) {
        const fail = (message: string) => ({ok: false as const, message: `Item ${editIndex + 1}: ${message}`});
        const spans = findMatches(normalizedContent, normalizeFileText(edit.old_string));
        if (spans.length === 0) {
            return fail(`In ${path}, old_string was not found in the original version. Verify the target file and exact text with targeted search/read_file; do not retry unchanged. All items must match this file's original contents, not another file or content generated by earlier items.`);
        }
        if (!edit.replace_all && spans.length > 1) {
            return fail(`old_string in ${path} matched ${spans.length} locations at lines ${spans.slice(0, 8).map(span => lineRange(normalizedContent, span)).join(", ")}${spans.length > 8 ? ", …" : ""}. Provide unique context, or use replace_all=true after reading the whole current file.`);
        }
        if (edit.replace_all) {
            const observed = ctx.fileState.check(path, originalContent, {requireFullRead: true});
            if (!observed.ok) return fail(`replace_all requires reading the entire file in its current version with read_file (${observed.reason}). Use a unique local replacement to modify only one location.`);
        }
        const newString = normalizeFileText(edit.new_string);
        for (const span of spans) replacements.push({...span, newString, editIndex});
    }

    replacements.sort((a, b) => a.start - b.start);
    for (let i = 1; i < replacements.length; i++) {
        const previous = replacements[i - 1]!;
        const current = replacements[i]!;
        if (current.start < previous.end) {
            return {ok: false, message: `Item ${previous.editIndex + 1} (lines ${lineRange(normalizedContent, previous)}) overlaps item ${current.editIndex + 1} (lines ${lineRange(normalizedContent, current)}). Combine them into one unambiguous replacement.`};
        }
    }
    return {
        ok: true,
        value: {
            originalContent,
            normalizedContent,
            changedSinceRead: !state.ok && state.reason === "stale",
            replacements,
        },
    };
}

export const editFileTool: Tool<typeof inputSchema> = {
    name: "edit_file",
    description:
        "Apply exact, non-overlapping replacements to one current file using the edits array. Each old_string must identify one location; no prior read_file receipt is required for local edits. Use read_file or Bash to inspect unfamiliar code before choosing changes. All items target the same original version, never text created by earlier items. replace_all=true requires a full read_file of the current file. Matching normalizes line endings and, only if exact matching fails, typographic quotes; indentation is significant. Every item is validated before one atomic write, and a concurrent file change aborts the write. Preserve context and exclude displayed line numbers. Group related non-overlapping changes in one call.",
    parameters: inputSchema,
    isReadOnly: () => false,
    getDefaultApprovalScope: ({path}) => ({kind: "workspace", path}),
    async checkPermissions({path, edits}, ctx) {
        const absPath = resolveToolPath(ctx.cwd, path);
        if (ctx.memoryFiles?.classify(absPath)) {
            return {behavior: "allow" as const};
        }

        const preview = edits.slice(0, 8).map((edit, index) =>
            `Item ${index + 1} (replace_all=${edit.replace_all}):\n${formatDiff(edit.old_string, edit.new_string)}`
        ).join("\n");
        const remaining = edits.length > 8 ? `\nPlus ${edits.length - 8} items; see tool arguments for the full input.` : "";
        return {
            behavior: "ask" as const,
            message: `About to modify ${path}(${edits.length} items):\n ${preview}${remaining}\nRun this command?`,
        };
    },
    execute: async (
        {path, edits: requestedEdits},
        ctx
    ) => {
        const absPath = resolveToolPath(ctx.cwd, path);
        const validation = await validateEdits(absPath, requestedEdits, ctx);
        if (!validation.ok) {
            return {
                content: `Edit failed: ${validation.message} No file was written. Use read_file at the failed location, verify the content, then edit again.`,
                outcome: "failed" as const,
            };
        }

        const {
            originalContent,
            normalizedContent,
            changedSinceRead,
            replacements,
        } = validation.value;
        const count = replacements.length;

        const newContent = applyReplacements(originalContent, replacements);
        const edits = replacements.map(span => ({start: Buffer.byteLength(normalizedContent.slice(0, span.start)),
            end: Buffer.byteLength(normalizedContent.slice(0, span.end)), insertedBytes: Buffer.byteLength(span.newString)}));

        if (ctx.memoryFiles?.classify(absPath)) {
            ctx.memoryFiles.validateWrite(absPath, newContent);
        }

        if (newContent === originalContent) {
            return `No changes needed for ${path}(content unchanged)`;
        }

        const change = createFileChange({
            path: displayToolPath(ctx.cwd, absPath),
            kind: "update",
            oldContent: originalContent,
            newContent,
            replacements: count,
        });

        await commitFileWrite({
            coordinator: ctx.fileCommits,
            signal: ctx.signal,
            path: absPath,
            beforeContent: originalContent,
            afterContent: newContent,
        });
        if (ctx.memoryFiles?.classify(absPath)) ctx.memoryFiles.written(absPath, newContent, false);
        ctx.fileState.recordWrite({
            path: absPath,
            content: newContent,
            beforeContent: originalContent,
            edits,
        });
        const result =
            `Modified ${path} (replaced ${count} matches)` + (changedSinceRead
                ? "\nThe file changed since its last recorded read. Only the requested matches were replaced; other current content was preserved. Inspect surrounding code before changes that depend on it." : "");
        return {
            content: result,
            displayContent: result,
            uiData: {type: "file_change", change},
        };
    },
};

// Helpers for edit_file.

// Small diff preview showing initial old/new lines.
function formatDiff(oldStr: string, newStr: string): string {
    const oldPreview = truncate(oldStr, 200);
    const newPreview = truncate(newStr, 200);
    return `- ${oldPreview}\n+ ${newPreview}`;
}

function truncate(s: string, max: number): string {
    if (s.length <= max) return JSON.stringify(s);
    return JSON.stringify(s.slice(0, max)) + "...";
}
